http:
  port: "8081"
  host: "localhost"

mysql:
  server: "sql6.freemysqlhosting.net"
  dbname: "sql6470089"
  username: "sql6470089"
  password: "4eYEIs3lFb"
  port: "3306"

app:
  home: "C:/Users/kowshalyab/Documents/GitHub/car-booking/src/main/resources/examples"
